### ISSUE TITLE
jonathanBrandes recommendations for things to do

### ISSUE THREAD

**Issue by jonathanBrandes** [githubteacher/developers-april-27#17]
# Places to see in the South Bay (Los Angeles)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-[x] Teledyne Controls training room
-[ ] Manhattan Beach
-[ ] Hermosa Beach

![Surfer](C:index.jpg)

**Comment by nchervonaya** [comment]
not _**# sure if a training room is a fun.**_
