### ISSUE TITLE
githubteacher recommendations for things to do 

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/developers-april-27#3]
## Recommendations for things to do in NC
- [x] Create a branch
- [x] Add a file
- [x] Commit my file
- [x] Open a pull request
- [x] Collaborate with my class mate
- [x] Get a :+1: from my team mates
- [x] :ship: it!
  How come I can edit anyone's comments???

**Comment by githubteacher** [comment]
@brianamarie anything else I need to add?

**Comment by brianamarie** [comment]
@githubteacher 👍 Looks good to me!
